apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-05-06T20:23:44Z"
  generation: 1
  labels:
    app: myphp
  name: myphp
  namespace: default
  resourceVersion: "1847907"
  selfLink: /apis/apps/v1/namespaces/default/deployments/myphp
  uid: 0d6ec504-072b-446a-b27d-4025f15dcf81
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: myphp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myphp
    spec:
      containers:
      - image: localhost:32000/php-apache
        imagePullPolicy: Always
        name: php-apache
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-05-06T20:23:46Z"
    lastUpdateTime: "2022-05-06T20:23:46Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-05-06T20:23:44Z"
    lastUpdateTime: "2022-05-06T20:23:46Z"
    message: ReplicaSet "myphp-5cc74b75df" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
